<?php

namespace App\Enums;

enum StatutDossier: string
{

    
    case EN_ATTENTE_VALIDATION = 'EN ATTENTE VALIDATION';
    case VALIDE = 'VALIDE';
    case REJETE = 'REJETE';

    case EN_ATTENTE_PROFORMA = 'EN ATTENTE PROFORMA';
    case EN_ATTENTE_PROFORMA_COMPLEMENTAIRE = 'EN ATTENTE PROFORMA COMPLEMENTAIRE';
    case EN_ATTENTE_PROFORMA_RELANCE   = 'EN ATTENTE PROFORMA RELANCE';
    case PROFORMA_VALIDE   = 'PROFORMA VALIDE';
    case PROFORMA_COMPLEMENTAIRE_VALIDE   = 'PROFORMA COMPLEMENTAIRE VALIDE';
    case PROFORMA_REJETEE = 'PROFORMA REJETEE';

    case EN_ATTENTE_FACTURE    = 'EN ATTENTE FACTURE';
    case EN_ATTENTE_FACTURE_COMPLEMENTAIRE    = 'EN ATTENTE FACTURE COMPLEMENTAIRE';
    case EN_ATTENTE_FACTURE_RELANCE     = 'EN ATTENTE FACTURE RELANCE';
    case FACTURE_VALIDE   = 'FACTURE VALIDE';
    case FACTURE_COMPLEMENTAIRE_VALIDE   = 'FACTURE COMPLEMENTAIRE VALIDE';

    case EN_ATTENTE_BAD     = 'EN ATTENTE BAD';
    case EN_ATTENTE_BAD_RELANCE     = 'EN ATTENTE BAD RELANCE';
    case BAD_VALIDE   = 'BAD VALIDE';

    case REMISE_EN_ATTENTE_VALIDATION_FACTURATION = 'REMISE_EN ATTENTE VALIDATION FACTURATION';
    case REMISE_EN_ATTENTE_VALIDATION_DIRECTION = 'REMISE_EN ATTENTE VALIDATION DIRECTION';
    case REMISE_VALIDE = 'REMISE_VALIDE';
    case REMISE_REJETE = 'REMISE_REJETE';
}
